name: image-ranker
channels:
- defaults
dependencies:
- h5py>=2.7,<3
- hdf5>=1.8,<2
- mkl=2017.0.3
- pip=10.0.1
- python=3.6.6
- scipy=0.19.1
- zlib=1.2.11
- pip:
  - black==18.6b4
  - colorama==0.3.9
  - Keras==2.1.6
  - Pillow==5.1.0
  - six==1.11.0
  - tensorflow-gpu==1.9.0
  - tqdm==4.23.4
